project:
  type: book

book:
  title: "inclusive-meetings"
  author: "Jane Doe"
  date: "12/28/2021"
  chapters:
    - index.qmd
    - intro.qmd
    - checklist.qmd
    - cheatsheet.qmd
    - planning.qmd
    - opening.qmd
    - facilitation.qmd
    - responding.qmd
    - closing.qmd
    - followup.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreport

editor: visual

